Added pagination with continuation token for listing
payfunc/transactly pull request #17
Opened 2022-02-16 09:41 UTC by marcushanses

2022-02-16 12:44 UTC, nilssonemma approved these changes

2022-02-16 12:53 UTC, Magnus93 requested changes

2022-02-16 12:53 UTC, Magnus93 commented on Backend.ts
> +	): Promise<{ data: Document<T>[]; continuation: string | undefined }> {
```suggestion
	): Promise<{ data: Document<T>[]; continuation?: string }> {
```

2022-02-17 08:20 UTC, nilssonemma approved these changes

2022-02-17 09:31 UTC, robinnedergard approved these changes

2022-02-23 21:15 UTC, fredrikbryntesson approved these changes

2022-02-23 21:15 UTC, merged